### ISSUE TITLE
updated for fastai V2

### ISSUE THREAD

**Issue by nestordemeure** [oguiza/fastai_extensions#6]
Hello, I am the maintainer of the [fastai-extensions-repository](https://github.com/nestordemeure/fastai-extensions-repository) and I am currently updating my link and description to take into accout the fact that fastai V2 is now the default.

Are your extensions all up to date with V2 (by default I marked them as V1) ?

**Comment by oguiza** [comment]
Hi Nestor,
Thanks for your interest in this repo, and for updating your repo. I think it's super useful!
Unfortunately, I have not updated these extensions to v2. 
I just develop and share the functionality that I need for my own operations. So I might update some of these in the future, but don't have any concrete plans to do so.

**Comment by nestordemeure** [comment]
Ok, thank you for the information. Don't hesitate to ping me if you update your code (or publish another project that could be listed in the repo).
